### ISSUE TITLE
Simulate genes are regulated by more than one peak

### ISSUE THREAD

**Issue by fanyue322** [ConesaLab/MOSim#4]
Hi developers,

Thanks for your excellent work!

After reviewing the provided tutorial, I noticed that the examples are primarily focused on simulating data where each gene is regulated by 1 peak. I am interested in exploring scenarios where genes are regulated by more than two peaks. For example, ~10 peaks are located in the gene body region and 2 of them are associated with the gene expression level.

Could you please advise if there is a possibility to extend the functionality of MOSim to accommodate this requirement?

Thank you for your feedbacks

Best regards

**Comment by carolinamonzo** [comment]
Hi @fanyue322,

Yes, the simulation of multi-omics datasets for bulk data allows for this. You only need to provide an association dataframe where the gene name is repeated as many times as peaks are regulating it. For example:
geneID peakID
gene1 peak1
gene1 peak2
gene1 peak3
...
About simulating this in the single cell part, unfortunately I'm still working on it.

Best wishes
