### ISSUE TITLE
How to handle the non-integar data stored in counts slot

### ISSUE THREAD

**Issue by fanyue322** [ConesaLab/MOSim#5]
Hi developers,

I have simulated a multi-omics data, and I found the RNA and ATAC data are stored in a Seurat Assay class. Specifically, I observed that both the RNA and ATAC data are stored in the counts slot, which is typically reserved for integer values. However, the data in this slot are non-integer and match the data in the data slot.

Is the MOSim tool designed to simulate only normalized data? If so, should we be treating the data as pre-normalized?

Regarding the normalization of ATAC data, what is the approach been used? Is it  log normalization or TF-IDF?

Thank you for your feedbacks

Best regards

**Comment by carolinamonzo** [comment]
Hi @fanyue322,

Thanks for using MOSim! 

To simulate the biological variability between samples for the single-cell version, MOSim needs to get a grasp of the gene expression patterns within each celltype. So the original count values are scaled using scran::computeSumFactors, which basically makes a pseudo-cell for each celltype, and uses it to define a size factor for the cells for each celltype as the median ratio between the count sums and the average across all genes. And then uses those size factors to scale the cells of each celltype using scater::normalizeCounts. This gives us a better ground to simulate the replicates and groups, and it's the reason why both the data and counts slots have the same values (float). The data is not log-transformed, gone through TF-IDF,  or any other normalization, so it should be treated as pre-normalized.

For example, when I use the data simulated using sc_mosim, I usually log1p normalize both scRNA and scATAC, but you can choose other methods if you prefer :)

I hope this was helpful. Best wishes,
Carolina.

**Comment by fanyue322** [comment]
Many thanks! It is really helpful
